src/Entity/Question.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Stringable;

#[ORM\Entity(QuestionRepository::class)]
class Question implements Stringable
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id;

    #[ORM\Column]
    private ?string $name;

    /**
     * @Gedmo\Slug(fields={"name"})
     */
    #[ORM\Column(length: 100, unique: true)]
    private ?string $slug;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $question;

    #[ORM\ManyToOne(inversedBy: 'questions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $askedBy;

    #[ORM\Column]
    private int $votes = 0;

    /**
     * @var Collection<int,Answer>
     */
    #[ORM\OneToMany('question', Answer::class, orphanRemoval: true)]
    private Collection $answers;

    #[ORM\ManyToOne(inversedBy: 'questions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Topic $topic;

    #[ORM\Column]
    private bool $isApproved = false;

    #[ORM\ManyToOne]
    private User $updatedBy;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getAskedBy(): ?User
    {
        return $this->askedBy;
    }

    public function setAskedBy(?User $askedBy): self
    {
        $this->askedBy = $askedBy;

        return $this;
    }

    public function getVotesString(): string
    {
        $prefix = $this->getVotes() >= 0 ? '+' : '-';

        return sprintf('%s %d', $prefix, abs($this->getVotes()));
    }

    public function getVotes(): int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function upVote(): self
    {
        ++$this->votes;

        return $this;
    }

    public function downVote(): self
    {
        --$this->votes;

        return $this;
    }

    /**
     * @return Collection<int,Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    public function getTopic(): ?Topic
    {
        return $this->topic;
    }

    public function setTopic(?Topic $topic): self
    {
        $this->topic = $topic;

        return $this;
    }

    public function getIsApproved(): bool
    {
        return $this->isApproved;
    }

    public function setIsApproved(bool $isApproved): void
    {
        $this->isApproved = $isApproved;
    }

    public function getUpdatedBy(): ?User
    {
        return $this->updatedBy;
    }

    public function setUpdatedBy(User $updatedBy): void
    {
        $this->updatedBy = $updatedBy;
    }
}

src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Stringable;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(UserRepository::class)]
#[ORM\Table('`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, Stringable
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email;

    /**
     * @var string[]
     */
    #[ORM\Column(type: Types::JSON)]
    private array $roles = [];

    /**
     * The hashed password.
     */
    #[ORM\Column]
    private ?string $password;

    /**
     * The plain non-persisted password.
     */
    private ?string $plainPassword;

    #[ORM\Column]
    private bool $enabled = true;

    #[ORM\Column]
    private ?string $firstName;

    #[ORM\Column]
    private ?string $lastName;

    #[ORM\Column(nullable: true)]
    private ?string $avatar;

    /**
     * @var Collection<int,Question>
     */
    #[ORM\OneToMany('askedBy', Question::class)]
    private Collection $questions;

    /**
     * @var Collection<int,Answer>
     */
    #[ORM\OneToMany('answeredBy', Answer::class)]
    private Collection $answers;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->answers = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->getFullName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param string[] $roles
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): string
    {
        return (string) $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): void
    {
        $this->enabled = $enabled;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): void
    {
        $this->firstName = $firstName;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): void
    {
        $this->lastName = $lastName;
    }

    public function getFullName(): ?string
    {
        return $this->firstName.' '.$this->lastName;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function getAvatarUrl(): ?string
    {
        if (!$this->avatar) {
            return null;
        }

        if (false !== strpos($this->avatar, '/')) {
            return $this->avatar;
        }

        return sprintf('/uploads/avatars/%s', $this->avatar);
    }

    public function setAvatar(?string $avatar): void
    {
        $this->avatar = $avatar;
    }

    /**
     * @return Collection<int,Question>
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setAskedBy($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getAskedBy() === $this) {
                $question->setAskedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int,Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setAnsweredBy($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getAnsweredBy() === $this) {
                $answer->setAnsweredBy(null);
            }
        }

        return $this;
    }
}

src/Controller/QuestionController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Question;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class QuestionController extends AbstractController
{
    public function __construct(private readonly LoggerInterface $logger, private readonly bool $isDebug)
    {
    }

    #[Route('/', name: 'app_homepage')]
    public function homepage(QuestionRepository $repository): Response
    {
        $questions = $repository->findAllApprovedOrderedByNewest();

        return $this->render('question/homepage.html.twig', [
            'questions' => $questions,
        ]);
    }

    #[Route('/questions/new')]
    public function new(): Response
    {
        return new Response('Sounds like a GREAT feature for V2!');
    }

    #[Route('/questions/{slug}', name: 'app_question_show')]
    public function show(Question $question): Response
    {
        if (!$question->getIsApproved()) {
            throw $this->createNotFoundException(sprintf('Question %s has not been approved yet', $question->getId()));
        }

        if ($this->isDebug) {
            $this->logger->info('We are in debug mode!');
        }

        return $this->render('question/show.html.twig', [
            'question' => $question,
        ]);
    }

    #[Route('/questions/{slug}/vote', name: 'app_question_vote', methods: 'POST')]
    public function questionVote(Question $question, Request $request, EntityManagerInterface $entityManager): Response
    {
        $direction = $request->request->get('direction');

        if ('up' === $direction) {
            $question->upVote();
        } elseif ('down' === $direction) {
            $question->downVote();
        }

        $entityManager->flush();

        return $this->redirectToRoute('app_question_show', [
            'slug' => $question->getSlug(),
        ]);
    }
}

templates/question/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="jumbotron-img p-2 mb-2">
    <div class="container">
        <h1 class="display-4">Your Questions Answered</h1>
        <div class="lead">And even answers for those questions you didn't think to ask!</div>
    </div>
</div>
<div class="container">
    <div class="row mb-3">
        <div class="col">
            <button class="btn btn-question">Ask a Question</button>
        </div>
    </div>
    <div class="row">
        {% for question in questions %}
        <div class="col-12 mb-3">
            <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                <div class="q-container p-4">
                    <div class="row">
                        <div class="col-2 text-center">
                            <img src="{{ asset(question.askedBy.avatarUrl) }}" width="100" height="100"  alt="Tisha avatar">
                            <div class="vote-arrows vote-arrows-alt flex-fill pt-2" style="min-width: 90px;">
                                <span>{{ question.votesString}} votes</span>
                            </div>
                        </div>
                        <div class="col">
                            <a class="q-title" href="{{ path('app_question_show', { slug: question.slug }) }}"><h2>{{ question.name }}</h2></a>
                            <div class="q-display p-3">
                                <i class="fa fa-quote-left mr-3"></i>
                                <p class="d-inline">{{ question.question|parse_markdown }}</p>
                                <p class="pt-4"><strong>--{{ question.askedBy.fullName }}</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="answer-link" href="{{ path('app_question_show', { slug: question.slug }) }}" style="color: #fff;">
                    <p class="q-display-response text-center p-3">
                        <i class="fa fa-magic magic-wand"></i> {{ question.answers|length }} answers
                    </p>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question: {{ question.name }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="my-4">
                    Topic:
                    <a href="#link-to-topic">{{ question.topic.name }}</a>
                </h2>
                <h2 class="my-4">Question:</h2>
                <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                    <div class="q-container-show p-4">
                        <div class="row">
                            <div class="col-2 text-center">
                                <img src="{{ asset(question.askedBy.avatarUrl) }}" width="100" height="100"
                                     alt="Tisha avatar">
                                <div class="mt-3">
                                    <small>
                                        {% if question.isApproved %}
                                            Asked <br>
                                            {{ question.createdAt|ago }}
                                        {% else %}
                                            (unpublished)
                                        {% endif %}
                                    </small>

                                    <form method="post"
                                          action="{{ path('app_question_vote', { slug: question.slug }) }}">
                                        <div class="vote-arrows vote-arrows-alt flex-fill pt-2"
                                             style="min-width: 90px;">
                                            <button class="vote-up btn btn-link" name="direction" value="up">
                                                <i class="far fa-arrow-alt-circle-up"></i>
                                            </button>
                                            <button class="vote-down btn btn-link" name="direction" value="down">
                                                <i class="far fa-arrow-alt-circle-down"></i>
                                            </button>
                                            <span>{{ question.votesString }}</span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col">
                                <div class="d-flex justify-content-between">
                                    <h1 class="q-title-show">{{ question.name }}</h1>
                                    {% if is_granted('ROLE_ADMIN') %}
                                        <a href="{{ ea_url()
                                            .setController('App\\Controller\\Admin\\QuestionCrudController')
                                            .setAction('edit')
                                            .setEntityId(question.id) }}"
                                           class="text-white">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="q-display p-3">
                                    <i class="fa fa-quote-left mr-3"></i>
                                    <p class="d-inline">{{ question.question|parse_markdown }}</p>
                                    <p class="pt-4"><strong>--{{ question.askedBy.fullName }}</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-between my-4">
            <h2 class="">Answers <span style="font-size:1.2rem;">({{ question.answers|length }})</span></h2>
            <button class="btn btn-sm btn-secondary">Submit an Answer</button>
        </div>

        <ul class="list-unstyled">
            {% for answer in question.answers %}
                <li class="mb-4">
                    <div class="d-flex justify-content-center">
                        <div class="mr-2 pt-2">
                            <img src="{{ asset(answer.answeredBy.avatarUrl) }}"
                                 width="50"
                                 height="50"
                                 alt="Tisha avatar">
                        </div>
                        <div class="mr-3 pt-2">
                            {{ answer.answer|parse_markdown }}
                            <p>-- {{ answer.answeredBy.fullName }}</p>
                        </div>
                        <div class="vote-arrows flex-fill pt-2 js-vote-arrows" style="min-width: 90px;">
                            <button class="vote-up btn btn-link" name="direction" value="up">
                                <i class="far fa-arrow-alt-circle-up"></i>
                            </button>
                            <button class="vote-down btn btn-link" name="direction" value="down">
                                <i class="far fa-arrow-alt-circle-down"></i>
                            </button>
                            <span>{{ answer.votesString }}</span>
                        </div>
                    </div>
                </li>
            {% else %}
                <li class="mb-4">
                    <div class="d-flex justify-content-center">
                        Be the first to answer!
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}